import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/ska00/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve('dist'),output=path.resolve('test-results');await fs.mkdir(output,{recursive:true});
const profile=await fs.mkdtemp(path.join(output,'browser-profile-'));
const origin='https://natural-english.test';
const sample=JSON.parse(await fs.readFile('Natural-English-Sample.json','utf8'));
const results=[],errors=[];let context,page;
async function start(){
 context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1280,height:800},acceptDownloads:true,serviceWorkers:'block',reducedMotion:'reduce'});
 await context.route('**/*',async route=>{
   const url=new URL(route.request().url());if(url.origin!==origin)return route.abort();
   const file=path.resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
   if(!file.startsWith(root+path.sep))return route.abort();
   try {const body=await fs.readFile(file);const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)];await route.fulfill({status:200,contentType:type,body});}catch{await route.fulfill({status:404,body:'Not found'});}
 });
 // Only capture calls to the TTS boundary; no claim about audible output.
 await context.addInitScript(()=>{window.__spoken=[];speechSynthesis.speak=utterance=>{window.__spoken.push({text:utterance.text,lang:utterance.lang,rate:utterance.rate});};});
 page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 page.on('dialog',dialog=>dialog.type()==='prompt'?dialog.accept('전체 삭제'):dialog.accept());
 await page.goto(origin);await page.locator('.card').first().waitFor();
}
async function check(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}
async function importJSON(data,name='lesson.json'){await page.locator('#import-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>!document.getElementById('import-lesson').disabled);}
try{
 await start();
 await check('Main Import button opens file chooser',async()=>{const chosen=page.waitForEvent('filechooser',{timeout:5000});await page.locator('#import-lesson').click();await (await chosen).setFiles([]);});
 await check('Sample JSON Import and 5 expressions',async()=>{await importJSON(sample);assert.equal(await page.locator('.card').count(),5);assert.equal(await page.locator('#library-button').textContent(),'2026-09-13 ▼');assert.match(await page.locator('#import-status').textContent(),/2026년 9월 13일 교재를 불러왔습니다/);});
 await check('Explain, recommendation and Korean examples',async()=>{await page.locator('.explain-button').first().click();assert.equal(await page.locator('.explanation').first().isVisible(),true);assert.ok((await page.locator('.explanation').first().textContent()).includes('뉘앙스'));assert.ok((await page.locator('.card').last().textContent()).includes('알아듣는 정도면 충분'));});
 await check('TTS calls and Slow rate (audio boundary stubbed)',async()=>{await page.locator('#speed').selectOption('0.75');await page.locator('.card-actions button').first().click();const call=await page.evaluate(()=>window.__spoken.at(-1));assert.equal(call.lang,'en-US');assert.equal(call.rate,0.75);assert.equal(call.text,sample.expressions[0].expression);});
 await check('Practice 3/5, Favorite and reload persistence',async()=>{await page.locator('.favorite').first().click();await page.waitForFunction(()=>document.querySelector('.favorite').getAttribute('aria-pressed')==='true');await page.locator('.practice-button').first().click();for(let i=1;i<=3;i++){await page.locator('#manual').click();await page.waitForFunction(n=>document.querySelector('#practice-count').textContent.startsWith(n+' /'),i);}await page.locator('#close-practice').click();await page.reload();await page.locator('.card').first().waitFor();assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'true');await page.locator('.practice-button').first().click();assert.match(await page.locator('#practice-count').textContent(),/^3 \/ 5/);});
 await check('Practice 5/5 auto completion and no sixth count',async()=>{for(let i=4;i<=5;i++){await page.locator('#manual').click();await page.waitForFunction(n=>document.querySelector('#practice-count').textContent.startsWith(n+' /'),i);}assert.equal(await page.locator('#manual').isDisabled(),true);await page.locator('#close-practice').click();assert.equal(await page.locator('.complete-button').first().getAttribute('aria-pressed'),'true');});
 await check('English Only / Korean toggle',async()=>{await page.locator('#bilingual').click();assert.equal(await page.locator('.korean').first().isVisible(),true);await page.locator('#english-only').click();assert.equal(await page.locator('.korean').first().isVisible(),false);});
 await check('Vocabulary selection and translated example',async()=>{await page.locator('.word').first().click();assert.match(await page.locator('#vocabulary h3').textContent(),/a lot on my plate/);assert.ok((await page.locator('#vocabulary').textContent()).includes(sample.vocabulary[0].exampleKo));});
 await check('Tablet landscape and portrait responsive layout',async()=>{const left=await page.locator('.expressions-section').boundingBox(),right=await page.locator('.reading-section').boundingBox(),vocab=await page.locator('.vocabulary-section').boundingBox();assert.ok(right.x>left.x+left.width);assert.ok(vocab.y>right.y);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(400);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,'tablet-landscape.png'),fullPage:false});await page.setViewportSize({width:800,height:1280});const a=await page.locator('.expressions-section').boundingBox(),b=await page.locator('.reading-section').boundingBox();assert.ok(b.y>a.y+a.height);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(output,'tablet-portrait.png'),fullPage:false});await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:1280,height:800});});
 await check('Date navigation and Library selection',async()=>{await importJSON({...sample,date:'2026-09-14',title:'Second lesson'});await page.locator('#previous-day').click();await page.waitForFunction(()=>document.querySelector('#library-button').textContent==='2026-09-13 ▼');assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'true');await page.locator('#next-day').click();await page.waitForFunction(()=>document.querySelector('#library-button').textContent==='2026-09-14 ▼');assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'false');await page.locator('#library-button').click();await page.locator('.library-choose').filter({hasText:'2026-09-13'}).click();});
 await check('IndexedDB and full browser restart persistence',async()=>{const count=await page.evaluate(async()=>{const module=await import('/library-db.js');return (await module.snapshot()).lessons.length;});assert.equal(count,3);await context.close();await start();assert.equal(await page.locator('#library-button').textContent(),'2026-09-13 ▼');assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'true');await page.locator('.practice-button').first().click();assert.match(await page.locator('#practice-count').textContent(),/^5 \/ 5/);await page.locator('#close-practice').click();});
 await check('Malformed and invalid JSON preserve active lesson',async()=>{await importJSON({...sample,date:'invalid'});assert.match(await page.locator('#import-status').textContent(),/불러오기 실패/);assert.equal(await page.locator('.card').count(),5);await page.locator('#import-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{')});await page.waitForFunction(()=>!document.querySelector('#import-lesson').disabled);assert.match(await page.locator('#import-status').textContent(),/JSON 문법/);});
 let backup;
 await check('Library Export includes all lessons and progress',async()=>{await page.locator('#settings-button').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export-library').click();const download=await downloadPromise;const file=path.join(output,'export.json');await download.saveAs(file);backup=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(backup.lessons.length,3);assert.ok(backup.progress.some(p=>p.date==='2026-09-13'&&p.practiceCount===5&&p.favorite&&p.completed));await page.locator('#close-settings').click();});
 await check('Single deletion removes lesson and associated progress',async()=>{await page.locator('#library-button').click();await page.getByRole('button',{name:'2026-09-13 교재 삭제',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#library-list').textContent.includes('2026-09-13'));const p=await page.evaluate(async()=>(await (await import('/library-db.js')).snapshot()).progress);assert.ok(p.every(p=>p.date!=='2026-09-13'));await page.locator('#close-library').click();});
 await check('Delete all, empty state and backup restore',async()=>{await page.locator('#settings-button').click();await page.locator('#delete-all').click();await page.waitForFunction(()=>document.querySelectorAll('.card').length===0);await page.reload();await page.waitForFunction(()=>!document.querySelector('#import-lesson').disabled);assert.equal(await page.locator('.card').count(),0);await importJSON(backup,'backup.json');assert.equal(await page.locator('.card').count(),5);await page.locator('#previous-day').click();await page.waitForFunction(()=>document.querySelector('#library-button').textContent==='2026-09-13 ▼');assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'true');});
 await check('Same-date replacement keeps matching progress',async()=>{await importJSON({...sample,title:'Updated title'});assert.equal(await page.locator('.favorite').first().getAttribute('aria-pressed'),'true');await page.locator('.practice-button').first().click();assert.match(await page.locator('#practice-count').textContent(),/^5 \/ 5/);await page.locator('#reset-practice').click();await page.waitForFunction(()=>document.querySelector('#practice-count').textContent.startsWith('0 /'));await page.locator('#close-practice').click();assert.equal(await page.locator('.complete-button').first().getAttribute('aria-pressed'),'false');});
 await check('Recognition unsupported and TTS unsupported graceful fallback',async()=>{await context.addInitScript(()=>{window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined;delete window.speechSynthesis;});await page.reload();await page.locator('.card').first().waitFor();await page.locator('.practice-button').first().click();assert.equal(await page.locator('#recognize').isDisabled(),true);await page.locator('#manual').click();await page.waitForFunction(()=>document.querySelector('#practice-count').textContent.startsWith('1 /'));await page.locator('#close-practice').click();await page.locator('.card-actions button').first().click();assert.match(await page.locator('#notice').textContent(),/지원하지 않습니다/);});
 assert.deepEqual(errors,[]);results.push({name:'No uncaught browser errors',status:'PASS'});
}finally{if(context)await context.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify({results,errors,limitations:['HTTP routes supplied from local files without starting a server. Service Worker installation/offline cache not exercised.','TTS boundary captured; real audio and microphone require a device.']},null,2));}
