// Dependency-free classic bundle for file:// and normal PWA use.
import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'');
const model=read('dist/data-model.js').replace(/\bexport (?=(?:const|function|async function)\b)/g,'');
const database=read('dist/library-db.js').replace(/\bexport (?=(?:const|function|async function)\b)/g,'');
let app=read('dist/app.js').replace(/^import .*;\r?\n/gm,'');
if(/^import /m.test(app))throw new Error('Unknown import in app.js');
const starter=JSON.parse(read('dist/data/starter.json'));
app=app.replace("await getJSON('./data/starter.json')",'bundledStarter');
const bundle=`// Generated by scripts/build.mjs. Edit app.js, data-model.js and library-db.js instead.\n(()=>{\n'use strict';\nconst {parseImport,validateLesson,normalize,recommendationLabels}=(()=>{\n${model}\nreturn {parseImport,validateLesson,normalize,recommendationLabels};\n})();\nconst db=(()=>{\n${database}\nreturn {snapshot,saveProgress,setMeta,deleteLesson,clearLibrary,importLessons};\n})();\nconst bundledStarter=${JSON.stringify(starter)};\n${app}\n})();\n`;
fs.writeFileSync('dist/app.bundle.js',bundle);
console.log('Built dist/app.bundle.js (local-file compatible)');
